// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Container2;
void ui_event_TextArea1(lv_event_t * e);
lv_obj_t * ui_TextArea1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
void ui_event_TextArea2(lv_event_t * e);
lv_obj_t * ui_TextArea2;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label5;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Keyboard2;


// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
lv_obj_t * ui_Screen7;
lv_obj_t * ui_Image20;
void ui_event_Button22(lv_event_t * e);
lv_obj_t * ui_Button22;
lv_obj_t * ui_Label58;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label48;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label8;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label31;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label12;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Image25;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
void ui_event_Label14(lv_event_t * e);
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label52;
lv_obj_t * ui_Label54;
lv_obj_t * ui_Label55;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label77;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
lv_obj_t * ui_Label81;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_Label51;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
lv_obj_t * ui_Label74;
lv_obj_t * ui_Container11;
lv_obj_t * ui_Label56;
lv_obj_t * ui_Label9v;
lv_obj_t * ui_Label52v;
lv_obj_t * ui_Label54v;
lv_obj_t * ui_Label55v;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Image29;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Label92;
lv_obj_t * ui_Label93;
lv_obj_t * ui_Label94;
lv_obj_t * ui_Label95;
lv_obj_t * ui_Label64;
lv_obj_t * ui_Label91;
lv_obj_t * ui_Label47;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label86;
lv_obj_t * ui_Label49;
lv_obj_t * ui_Label89;
lv_obj_t * ui_Label87;
lv_obj_t * ui_Label90;
lv_obj_t * ui_Label45;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Label88;
lv_obj_t * ui_Label67;
lv_obj_t * ui_Label78;
lv_obj_t * ui_Label80;
lv_obj_t * ui_Container10;
lv_obj_t * ui_Label59;
lv_obj_t * ui_Label66;
lv_obj_t * ui_Label71;
lv_obj_t * ui_Label72;
lv_obj_t * ui_Label73;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
void ui_event_Label10(lv_event_t * e);
lv_obj_t * ui_Label10;


// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
lv_obj_t * ui_Screen6;
lv_obj_t * ui_Image31;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
void ui_event_Label13(lv_event_t * e);
lv_obj_t * ui_Label13;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Switch4;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Button30;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Button32;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Button31;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Button33;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Button34;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Button36;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Button38;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Button39;
lv_obj_t * ui_Label43;
lv_obj_t * ui_Button40;
lv_obj_t * ui_Label44;
lv_obj_t * ui_Button41;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Button42;
lv_obj_t * ui_Label50;
lv_obj_t * ui_Button43;
lv_obj_t * ui_Label53;
lv_obj_t * ui_Button44;
lv_obj_t * ui_Label57;
lv_obj_t * ui_Button45;
lv_obj_t * ui_Label68;
lv_obj_t * ui_Button46;
lv_obj_t * ui_Label69;
lv_obj_t * ui_Button37;
lv_obj_t * ui_Label70;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Button35;
lv_obj_t * ui_Label39;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Label79;
lv_obj_t * ui_Label60;
lv_obj_t * ui_Label61;
lv_obj_t * ui_Label62;
lv_obj_t * ui_Label63;
lv_obj_t * ui_Button21;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Button24;
lv_obj_t * ui_Label83;
lv_obj_t * ui_Button23;
lv_obj_t * ui_Label82;
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Button25;
lv_obj_t * ui_Label65;
lv_obj_t * ui____initial_actions0;
const lv_image_dsc_t * ui_imgset_[2] = {&ui_img_2_png, &ui_img_13_png};
const lv_image_dsc_t * ui_imgset_screen[1] = {&ui_img_screen9_png};
const lv_image_dsc_t * ui_imgset_1405107096[1] = {&ui_img_170934617};
const lv_image_dsc_t * ui_imgset_811311066[2] = {&ui_img_1168434321, &ui_img_760332301};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TextArea1);
    }
}
void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TextArea2);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        LOGIN_TASK(e);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        REGISTER_TASK(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen5_screen_init);
    }
}
void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen6_screen_init);
    }
}
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
    }
}
void ui_event_Label14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
    }
}
void ui_event_Button14(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) ai_btn_suggest(e);
}
void ui_event_Button15(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) ai_btn_diagnose(e);
}
void ui_event_Button13(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) ai_btn_evaluate(e);
}
void ui_event_Button17(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) ai_btn_maintain(e);
}
void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
    }
}
void ui_event_Label10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
    }
}
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
    }
}
void ui_event_Label13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
    }
}
void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen7_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui_Screen6_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
