// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Container2;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label5;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Keyboard2;
// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Image20;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label58;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label48;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label31;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label12;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image25;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
void ui_event_Label14(lv_event_t * e);
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Label55;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label77;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label81;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label51;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label74;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Label9v;
extern lv_obj_t * ui_Label52v;
extern lv_obj_t * ui_Label54v;
extern lv_obj_t * ui_Label55v;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Image29;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label92;
extern lv_obj_t * ui_Label93;
extern lv_obj_t * ui_Label94;
extern lv_obj_t * ui_Label95;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_Label91;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label86;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Label89;
extern lv_obj_t * ui_Label87;
extern lv_obj_t * ui_Label90;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label88;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Label78;
extern lv_obj_t * ui_Label80;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Label66;
extern lv_obj_t * ui_Label71;
extern lv_obj_t * ui_Label72;
extern lv_obj_t * ui_Label73;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
void ui_event_Label10(lv_event_t * e);
extern lv_obj_t * ui_Label10;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
void ui_event_Label13(lv_event_t * e);
extern lv_obj_t * ui_Label13;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Button30;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Button32;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Button31;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Button33;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Button34;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Button36;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Button38;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Button39;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Button40;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Button41;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Button42;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Button43;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Button44;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Button45;
extern lv_obj_t * ui_Label68;
extern lv_obj_t * ui_Button46;
extern lv_obj_t * ui_Label69;
extern lv_obj_t * ui_Button37;
extern lv_obj_t * ui_Label70;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Button35;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label79;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Label62;
extern lv_obj_t * ui_Label63;
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Label83;
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Label82;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_login_png);    // assets/login.png
LV_IMG_DECLARE(ui_img_screen9_png);    // assets/screen9.png
LV_IMG_DECLARE(ui_img_13_png);    // assets/13.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_170934617);    // assets/分组 6.png
LV_IMG_DECLARE(ui_img_1168434321);    // assets/组 3030.png
LV_IMG_DECLARE(ui_img_760332301);    // assets/组 367.png



LV_FONT_DECLARE(ui_font_chinese28);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
