// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#include "lvgl/lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

void LOGIN_TASK(lv_event_t * e);
void REGISTER_TASK(lv_event_t * e);
void temp_sensor1(lv_event_t * e);
void temp_sensor2(lv_event_t * e);
void light_sensor(lv_event_t * e);
void hum_sensor(lv_event_t * e);
void press_sensor(lv_event_t * e);

/* 视频播放器 */
void VIDEO_CONTINUE(lv_event_t * e);
void VIDEO_PAUSE(lv_event_t * e);
void VIDEO_FAST_FORWARD(lv_event_t * e);
void VIDEO_FAST_BACKWARD(lv_event_t * e);
void VIDEO_VOLUME_UP(lv_event_t * e);
void VIDEO_VOLUME_DOWN(lv_event_t * e);
void VIDEO_STOP(lv_event_t * e);

/* 图片浏览器 */
void IMG_PREV(lv_event_t * e);
void IMG_NEXT(lv_event_t * e);
void IMG_ZOOM_IN(lv_event_t * e);
void IMG_ZOOM_OUT(lv_event_t * e);
void IMG_BACK(lv_event_t * e);

/* 蓝牙 */
void BT_INIT(void);

/* STM32 传感器串口 */
void SENSOR_UART_INIT(void);

/* Screen2 PID 参数调节按钮 — 增氧机 */
void aer_kp_up(lv_event_t *e);
void aer_kp_dn(lv_event_t *e);
void aer_ki_up(lv_event_t *e);
void aer_ki_dn(lv_event_t *e);
void aer_kd_up(lv_event_t *e);
void aer_kd_dn(lv_event_t *e);

/* Screen2 PID — 循环水泵 */
void pump_kp_up(lv_event_t *e);
void pump_kp_dn(lv_event_t *e);
void pump_ki_up(lv_event_t *e);
void pump_ki_dn(lv_event_t *e);
void pump_kd_up(lv_event_t *e);
void pump_kd_dn(lv_event_t *e);

/* Screen2 PID — 投喂电机 */
void feed_kp_up(lv_event_t *e);
void feed_kp_dn(lv_event_t *e);
void feed_ki_up(lv_event_t *e);
void feed_ki_dn(lv_event_t *e);
void feed_kd_up(lv_event_t *e);
void feed_kd_dn(lv_event_t *e);

/* Screen2 设备开关 */
void sw_aerator(lv_event_t *e);
void sw_pump(lv_event_t *e);
void sw_feeder(lv_event_t *e);

/* Screen2 目标值调节 */
void do_target_up(lv_event_t *e);
void do_target_dn(lv_event_t *e);
void temp_target_up(lv_event_t *e);
void temp_target_dn(lv_event_t *e);

/* Screen2 + Screen6 定时刷新 */
void ui_S2_update_timer(lv_timer_t *t);

/* Screen4 AI 功能 — DeepSeek (Ollama) */
void ai_btn_evaluate(lv_event_t *e);    /* 一键评价 */
void ai_btn_diagnose(lv_event_t *e);    /* 故障诊断 */
void ai_btn_suggest(lv_event_t *e);     /* 智能建议 */
void ai_btn_maintain(lv_event_t *e);    /* 运维回答 */

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
