// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_chart_series_t * chart_ser[6];
lv_obj_t * chart_s6 = NULL;

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);

    ui_Image31 = lv_image_create(ui_Screen6);
    lv_image_set_src(ui_Image31, &ui_img_screen9_png);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Image31, -52);
    lv_obj_set_y(ui_Image31, -273);
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);

    ui_Label11 = lv_label_create(ui_Image31);
    lv_obj_set_width(ui_Label11, 196);
    lv_obj_set_height(ui_Label11, 32);
    lv_obj_set_x(ui_Label11, -226);
    lv_obj_set_y(ui_Label11, 69);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "传感器实时监控");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x25B782), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label11, lv_color_hex(0xE4FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label11, lv_color_hex(0x96FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ---- 传感器数据容器 (左) ---- */
    ui_Container3 = lv_obj_create(ui_Image31);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 253);
    lv_obj_set_height(ui_Container3, 280);
    lv_obj_set_x(ui_Container3, -215);
    lv_obj_set_y(ui_Container3, 245);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT); lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label4, -76); lv_obj_set_y(ui_Label4, -105);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "温度:");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT); lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label16, -75); lv_obj_set_y(ui_Label16, -60);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "湿度:");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT); lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label17, -65); lv_obj_set_y(ui_Label17, -15);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "溶解氧:");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT); lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label18, -68); lv_obj_set_y(ui_Label18, 30);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "pH值:");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT); lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label19, -71); lv_obj_set_y(ui_Label19, 75);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "浊度:");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT); lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label20, -73); lv_obj_set_y(ui_Label20, 115);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "光照:");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ---- 折线图 (右, 同宽同高同水平) ---- */
    lv_obj_t * chart = lv_chart_create(ui_Image31);
    chart_s6 = chart;
    lv_obj_set_size(chart, 400, 260);
    lv_obj_set_x(chart, 170);
    lv_obj_set_y(chart, 245);
    lv_obj_set_align(chart, LV_ALIGN_CENTER);
    lv_chart_set_type(chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(chart, 30);
    lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_Y, 0, 100);
    lv_chart_set_div_line_count(chart, 4, 5);

    lv_color_t colors[] = {
        lv_palette_main(LV_PALETTE_RED),
        lv_palette_main(LV_PALETTE_BLUE),
        lv_palette_main(LV_PALETTE_GREEN),
        lv_palette_main(LV_PALETTE_ORANGE),
        lv_palette_main(LV_PALETTE_PURPLE),
        lv_palette_main(LV_PALETTE_CYAN),
    };
    chart_ser[0] = lv_chart_add_series(chart, colors[0], LV_CHART_AXIS_PRIMARY_Y);
    chart_ser[1] = lv_chart_add_series(chart, colors[1], LV_CHART_AXIS_PRIMARY_Y);
    chart_ser[2] = lv_chart_add_series(chart, colors[2], LV_CHART_AXIS_PRIMARY_Y);
    chart_ser[3] = lv_chart_add_series(chart, colors[3], LV_CHART_AXIS_PRIMARY_Y);
    chart_ser[4] = lv_chart_add_series(chart, colors[4], LV_CHART_AXIS_PRIMARY_Y);
    chart_ser[5] = lv_chart_add_series(chart, colors[5], LV_CHART_AXIS_PRIMARY_Y);

    /* ---- 返回按钮 (右下) ---- */
    lv_obj_t * btn_back = lv_button_create(ui_Image31);
    lv_obj_set_size(btn_back, 100, 40);
    lv_obj_set_pos(btn_back, 300, 430);
    lv_obj_set_align(btn_back, LV_ALIGN_CENTER);
    lv_obj_t * lbl_back = lv_label_create(btn_back);
    lv_label_set_text(lbl_back, "返回");
    lv_obj_set_style_text_font(lbl_back, &ui_font_chinese28, 0);
    lv_obj_set_align(lbl_back, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(btn_back, ui_event_Button10, LV_EVENT_CLICKED, NULL);

    /* ---- 图例 (chart 右侧) ---- */
    const char *legends[] = {"温度", "湿度", "溶氧", "pH", "浊度", "光照"};
    for (int i = 0; i < 6; i++) {
        lv_obj_t * leg = lv_label_create(ui_Image31);
        lv_obj_set_width(leg, 60);
        lv_obj_set_height(leg, LV_SIZE_CONTENT);
        lv_obj_set_x(leg, 380);
        lv_obj_set_y(leg, 150 + i * 35);
        lv_obj_set_align(leg, LV_ALIGN_CENTER);
        lv_label_set_text(leg, legends[i]);
        lv_obj_set_style_text_color(leg, colors[i], 0);
        lv_obj_set_style_text_font(leg, &ui_font_chinese28, 0);
    }
}
