// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image1, &ui_img_screen9_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 2732
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1534
    lv_obj_set_x(ui_Image1, -46);
    lv_obj_set_y(ui_Image1, -288);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Image1);
    lv_obj_set_width(ui_Label21, 238);
    lv_obj_set_height(ui_Label21, 32);
    lv_obj_set_x(ui_Label21, -208);
    lv_obj_set_y(ui_Label21, 69);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "PID自动化控制面板");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x25B782), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label21, lv_color_hex(0xE4FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label21, lv_color_hex(0x96FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Image1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 378);
    lv_obj_set_height(ui_Container1, 156);
    lv_obj_set_x(ui_Container1, -102);
    lv_obj_set_y(ui_Container1, 355);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label22, 125);
    lv_obj_set_height(ui_Label22, 32);
    lv_obj_set_x(ui_Label22, -106);
    lv_obj_set_y(ui_Label22, -53);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "设备状态");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x25B782), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label22, lv_color_hex(0xE4FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label22, lv_color_hex(0x96FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -114);
    lv_obj_set_y(ui_Label23, -18);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "增氧机:");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -106);
    lv_obj_set_y(ui_Label24, 21);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "循环水泵:");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -107);
    lv_obj_set_y(ui_Label25, 59);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "投喂电机:");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Container1);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 5);
    lv_obj_set_y(ui_Switch1, -19);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Switch3 = lv_switch_create(ui_Container1);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 11);
    lv_obj_set_y(ui_Switch3, 57);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);


    ui_Switch4 = lv_switch_create(ui_Container1);
    lv_obj_set_width(ui_Switch4, 50);
    lv_obj_set_height(ui_Switch4, 25);
    lv_obj_set_x(ui_Switch4, 8);
    lv_obj_set_y(ui_Switch4, 20);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);


    ui_Container4 = lv_obj_create(ui_Image1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 681);
    lv_obj_set_height(ui_Container4, 155);
    lv_obj_set_x(ui_Container4, 42);
    lv_obj_set_y(ui_Container4, 178);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label26, 159);
    lv_obj_set_height(ui_Label26, 32);
    lv_obj_set_x(ui_Label26, -117);
    lv_obj_set_y(ui_Label26, -51);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "PID参数调节");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x25B782), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label26, lv_color_hex(0xE4FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label26, lv_color_hex(0x96FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -267);
    lv_obj_set_y(ui_Label27, 24);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "循环水泵:");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -279);
    lv_obj_set_y(ui_Label29, -13);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "增氧机:");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -264);
    lv_obj_set_y(ui_Label30, 58);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "投喂电机:");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button30 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button30, 43);
    lv_obj_set_height(ui_Button30, 28);
    lv_obj_set_x(ui_Button30, -58);
    lv_obj_set_y(ui_Button30, -13);
    lv_obj_set_align(ui_Button30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button30, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_Button30);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "KP-");

    ui_Button32 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button32, 43);
    lv_obj_set_height(ui_Button32, 28);
    lv_obj_set_x(ui_Button32, 106);
    lv_obj_set_y(ui_Button32, -11);
    lv_obj_set_align(ui_Button32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label36 = lv_label_create(ui_Button32);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "KI-");

    ui_Button31 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button31, 43);
    lv_obj_set_height(ui_Button31, 28);
    lv_obj_set_x(ui_Button31, 14);
    lv_obj_set_y(ui_Button31, -13);
    lv_obj_set_align(ui_Button31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_Button31);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "KI+");

    ui_Button33 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button33, 43);
    lv_obj_set_height(ui_Button33, 28);
    lv_obj_set_x(ui_Button33, 165);
    lv_obj_set_y(ui_Button33, 61);
    lv_obj_set_align(ui_Button33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label37 = lv_label_create(ui_Button33);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "KD+");

    ui_Button34 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button34, 43);
    lv_obj_set_height(ui_Button34, 28);
    lv_obj_set_x(ui_Button34, 271);
    lv_obj_set_y(ui_Button34, 61);
    lv_obj_set_align(ui_Button34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button34, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label38 = lv_label_create(ui_Button34);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -1);
    lv_obj_set_y(ui_Label38, 2);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "KD-");

    ui_Button3 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button3, 43);
    lv_obj_set_height(ui_Button3, 28);
    lv_obj_set_x(ui_Button3, -172);
    lv_obj_set_y(ui_Button3, -12);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "KP+");

    ui_Button36 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button36, 50);
    lv_obj_set_height(ui_Button36, 28);
    lv_obj_set_x(ui_Button36, -170);
    lv_obj_set_y(ui_Button36, 24);
    lv_obj_set_align(ui_Button36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button36, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label40 = lv_label_create(ui_Button36);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "KP+");

    ui_Button38 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button38, 43);
    lv_obj_set_height(ui_Button38, 28);
    lv_obj_set_x(ui_Button38, -54);
    lv_obj_set_y(ui_Button38, 25);
    lv_obj_set_align(ui_Button38, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button38, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label42 = lv_label_create(ui_Button38);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, 2);
    lv_obj_set_y(ui_Label42, 1);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "KP-");

    ui_Button39 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button39, 43);
    lv_obj_set_height(ui_Button39, 28);
    lv_obj_set_x(ui_Button39, 14);
    lv_obj_set_y(ui_Button39, 63);
    lv_obj_set_align(ui_Button39, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button39, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label43 = lv_label_create(ui_Button39);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "KI+");

    ui_Button40 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button40, 43);
    lv_obj_set_height(ui_Button40, 28);
    lv_obj_set_x(ui_Button40, 12);
    lv_obj_set_y(ui_Button40, 26);
    lv_obj_set_align(ui_Button40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button40, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label44 = lv_label_create(ui_Button40);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "KI+");

    ui_Button41 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button41, 43);
    lv_obj_set_height(ui_Button41, 28);
    lv_obj_set_x(ui_Button41, 112);
    lv_obj_set_y(ui_Button41, 64);
    lv_obj_set_align(ui_Button41, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button41, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label46 = lv_label_create(ui_Button41);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "KI-");

    ui_Button42 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button42, 43);
    lv_obj_set_height(ui_Button42, 28);
    lv_obj_set_x(ui_Button42, 109);
    lv_obj_set_y(ui_Button42, 25);
    lv_obj_set_align(ui_Button42, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button42, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label50 = lv_label_create(ui_Button42);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "KI-");

    ui_Button43 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button43, 43);
    lv_obj_set_height(ui_Button43, 28);
    lv_obj_set_x(ui_Button43, 160);
    lv_obj_set_y(ui_Button43, -12);
    lv_obj_set_align(ui_Button43, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button43, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label53 = lv_label_create(ui_Button43);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "KD+");

    ui_Button44 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button44, 43);
    lv_obj_set_height(ui_Button44, 28);
    lv_obj_set_x(ui_Button44, 162);
    lv_obj_set_y(ui_Button44, 24);
    lv_obj_set_align(ui_Button44, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button44, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button44, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label57 = lv_label_create(ui_Button44);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "KD+");

    ui_Button45 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button45, 43);
    lv_obj_set_height(ui_Button45, 28);
    lv_obj_set_x(ui_Button45, 267);
    lv_obj_set_y(ui_Button45, -10);
    lv_obj_set_align(ui_Button45, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button45, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label68 = lv_label_create(ui_Button45);
    lv_obj_set_width(ui_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label68, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label68, "KD-");

    ui_Button46 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button46, 43);
    lv_obj_set_height(ui_Button46, 28);
    lv_obj_set_x(ui_Button46, 270);
    lv_obj_set_y(ui_Button46, 25);
    lv_obj_set_align(ui_Button46, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button46, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label69 = lv_label_create(ui_Button46);
    lv_obj_set_width(ui_Label69, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label69, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label69, 1);
    lv_obj_set_y(ui_Label69, 0);
    lv_obj_set_align(ui_Label69, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label69, "KD-");

    ui_Button37 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button37, 43);
    lv_obj_set_height(ui_Button37, 28);
    lv_obj_set_x(ui_Button37, -51);
    lv_obj_set_y(ui_Button37, 63);
    lv_obj_set_align(ui_Button37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button37, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label70 = lv_label_create(ui_Button37);
    lv_obj_set_width(ui_Label70, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label70, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label70, 2);
    lv_obj_set_y(ui_Label70, 1);
    lv_obj_set_align(ui_Label70, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label70, "KP-");

    ui_Button10 = lv_button_create(ui_Image1);
    lv_obj_set_width(ui_Button10, 145);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, 364);
    lv_obj_set_y(ui_Button10, 488);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label32 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 16);
    lv_obj_set_y(ui_Label32, -3);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "返回");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button35 = lv_button_create(ui_Image1);
    lv_obj_set_width(ui_Button35, 50);
    lv_obj_set_height(ui_Button35, 28);
    lv_obj_set_x(ui_Button35, -128);
    lv_obj_set_y(ui_Button35, 240);
    lv_obj_set_align(ui_Button35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button35, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label39 = lv_label_create(ui_Button35);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 0);
    lv_obj_set_y(ui_Label39, 2);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "KP+");

    ui_Container5 = lv_obj_create(ui_Image1);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 239);
    lv_obj_set_height(ui_Container5, 159);
    lv_obj_set_x(ui_Container5, 246);
    lv_obj_set_y(ui_Container5, 353);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label79 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label79, 181);
    lv_obj_set_height(ui_Label79, 32);
    lv_obj_set_x(ui_Label79, -18);
    lv_obj_set_y(ui_Label79, -56);
    lv_obj_set_align(ui_Label79, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label79, "实时数据显示");
    lv_obj_set_style_text_color(ui_Label79, lv_color_hex(0x25B782), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label79, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label79, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label79, lv_color_hex(0xE4FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label79, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label79, lv_color_hex(0x96FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label79, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60, -63);
    lv_obj_set_y(ui_Label60, -22);
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, "溶解氧:");
    lv_obj_set_style_text_font(ui_Label60, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label61 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, -64);
    lv_obj_set_y(ui_Label61, 9);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "目标值:");
    lv_obj_set_style_text_font(ui_Label61, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label62 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label62, -72);
    lv_obj_set_y(ui_Label62, 37);
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "水温:");
    lv_obj_set_style_text_font(ui_Label62, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label63 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label63, -65);
    lv_obj_set_y(ui_Label63, 65);
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label63, "目标值:");
    lv_obj_set_style_text_font(ui_Label63, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button21 = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_Button21, 36);
    lv_obj_set_height(ui_Button21, 23);
    lv_obj_set_x(ui_Button21, 5);
    lv_obj_set_y(ui_Button21, 10);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Button21);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "+");

    ui_Button24 = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_Button24, 36);
    lv_obj_set_height(ui_Button24, 23);
    lv_obj_set_x(ui_Button24, 90);
    lv_obj_set_y(ui_Button24, 8);
    lv_obj_set_align(ui_Button24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label83 = lv_label_create(ui_Button24);
    lv_obj_set_width(ui_Label83, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label83, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label83, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label83, "-");

    ui_Button23 = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_Button23, 36);
    lv_obj_set_height(ui_Button23, 23);
    lv_obj_set_x(ui_Button23, 5);
    lv_obj_set_y(ui_Button23, 10);
    lv_obj_set_align(ui_Button23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label82 = lv_label_create(ui_Button23);
    lv_obj_set_width(ui_Label82, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label82, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label82, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label82, "+");

    ui_Button12 = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_Button12, 36);
    lv_obj_set_height(ui_Button12, 23);
    lv_obj_set_x(ui_Button12, 8);
    lv_obj_set_y(ui_Button12, 67);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "+");

    ui_Button25 = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_Button25, 36);
    lv_obj_set_height(ui_Button25, 23);
    lv_obj_set_x(ui_Button25, 94);
    lv_obj_set_y(ui_Button25, 67);
    lv_obj_set_align(ui_Button25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label65 = lv_label_create(ui_Button25);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, "-");

    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);

    /* PID 按钮 + 开关回调 */
    lv_obj_add_event_cb(ui_Button23,do_target_up,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button24,do_target_dn,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button12,temp_target_up,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button25,temp_target_dn,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button3,aer_kp_up,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button30,aer_kp_dn,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button31,aer_ki_up,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button32,aer_ki_dn,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button43,aer_kd_up,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button45,aer_kd_dn,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button36,pump_kp_up,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button38,pump_kp_dn,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button40,pump_ki_up,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button42,pump_ki_dn,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button44,pump_kd_up,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button46,pump_kd_dn,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button35,feed_kp_up,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button37,feed_kp_dn,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button39,feed_ki_up,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button41,feed_ki_dn,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button33,feed_kd_up,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Button34,feed_kd_dn,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_Switch1,sw_aerator,LV_EVENT_VALUE_CHANGED,NULL);
    lv_obj_add_event_cb(ui_Switch4,sw_pump,LV_EVENT_VALUE_CHANGED,NULL);
    lv_obj_add_event_cb(ui_Switch3,sw_feeder,LV_EVENT_VALUE_CHANGED,NULL);
}
