// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image29 = lv_image_create(ui_Screen5);
    lv_image_set_src(ui_Image29, &ui_img_screen9_png);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 2732
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 1534
    lv_obj_set_x(ui_Image29, -71);
    lv_obj_set_y(ui_Image29, -249);
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container8 = lv_obj_create(ui_Image29);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 326);
    lv_obj_set_height(ui_Container8, 203);
    lv_obj_set_x(ui_Container8, 195);
    lv_obj_set_y(ui_Container8, 161);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label92 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label92, 106);
    lv_obj_set_height(ui_Label92, 32);
    lv_obj_set_x(ui_Label92, -102);
    lv_obj_set_y(ui_Label92, -74);
    lv_obj_set_align(ui_Label92, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label92, "24h统计");
    lv_obj_set_style_text_color(ui_Label92, lv_color_hex(0x25B782), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label92, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label92, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label92, lv_color_hex(0xE4FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label92, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label92, lv_color_hex(0x96FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label92, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label93 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label93, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label93, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label93, -105);
    lv_obj_set_y(ui_Label93, -38);
    lv_obj_set_align(ui_Label93, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label93, "最大值:");
    lv_obj_set_style_text_font(ui_Label93, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label94 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label94, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label94, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label94, -105);
    lv_obj_set_y(ui_Label94, 2);
    lv_obj_set_align(ui_Label94, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label94, "最小值:");
    lv_obj_set_style_text_font(ui_Label94, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label95 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label95, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label95, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label95, -106);
    lv_obj_set_y(ui_Label95, 80);
    lv_obj_set_align(ui_Label95, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label95, "趋势:");
    lv_obj_set_style_text_font(ui_Label95, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label64 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label64, -5);
    lv_obj_set_y(ui_Label64, -72);
    lv_obj_set_align(ui_Label64, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label64, "DO");
    lv_obj_set_style_text_font(ui_Label64, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label91 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label91, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label91, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label91, -98);
    lv_obj_set_y(ui_Label91, 42);
    lv_obj_set_align(ui_Label91, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label91, "平均值:");
    lv_obj_set_style_text_font(ui_Label91, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, 85);
    lv_obj_set_y(ui_Label47, -74);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "Temp");
    lv_obj_set_style_text_font(ui_Label47, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Image29);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 326);
    lv_obj_set_height(ui_Container6, 217);
    lv_obj_set_x(ui_Container6, -140);
    lv_obj_set_y(ui_Container6, 165);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label86 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label86, 177);
    lv_obj_set_height(ui_Label86, 32);
    lv_obj_set_x(ui_Label86, -68);
    lv_obj_set_y(ui_Label86, -80);
    lv_obj_set_align(ui_Label86, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label86, "实时数据质量");
    lv_obj_set_style_text_color(ui_Label86, lv_color_hex(0x25B782), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label86, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label86, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label86, lv_color_hex(0xE4FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label86, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label86, lv_color_hex(0x96FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label86, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -108);
    lv_obj_set_y(ui_Label49, -44);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "溶解氧:");
    lv_obj_set_style_text_font(ui_Label49, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label89 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label89, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label89, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label89, -120);
    lv_obj_set_y(ui_Label89, -12);
    lv_obj_set_align(ui_Label89, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label89, "水温:");
    lv_obj_set_style_text_font(ui_Label89, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label87 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label87, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label87, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label87, -128);
    lv_obj_set_y(ui_Label87, 17);
    lv_obj_set_align(ui_Label87, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label87, "pH:");
    lv_obj_set_style_text_font(ui_Label87, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label90 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label90, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label90, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label90, -119);
    lv_obj_set_y(ui_Label90, 88);
    lv_obj_set_align(ui_Label90, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label90, "状态:");
    lv_obj_set_style_text_font(ui_Label90, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, -121);
    lv_obj_set_y(ui_Label45, 51);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "浊度:");
    lv_obj_set_style_text_font(ui_Label45, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Image29);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 326);
    lv_obj_set_height(ui_Container9, 173);
    lv_obj_set_x(ui_Container9, -138);
    lv_obj_set_y(ui_Container9, 377);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label88 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label88, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label88, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label88, -108);
    lv_obj_set_y(ui_Label88, -27);
    lv_obj_set_align(ui_Label88, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label88, "溶解氧:");
    lv_obj_set_style_text_font(ui_Label88, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label67 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label67, 118);
    lv_obj_set_height(ui_Label67, 32);
    lv_obj_set_x(ui_Label67, -96);
    lv_obj_set_y(ui_Label67, -61);
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label67, "趋势预测");
    lv_obj_set_style_text_color(ui_Label67, lv_color_hex(0x25B782), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label67, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label67, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label67, lv_color_hex(0xE4FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label67, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label67, lv_color_hex(0x96FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label67, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label78 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label78, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label78, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label78, -114);
    lv_obj_set_y(ui_Label78, 16);
    lv_obj_set_align(ui_Label78, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label78, "水温:");
    lv_obj_set_style_text_font(ui_Label78, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label80 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label80, -118);
    lv_obj_set_y(ui_Label80, 56);
    lv_obj_set_align(ui_Label80, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label80, "pH:");
    lv_obj_set_style_text_font(ui_Label80, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_Image29);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 326);
    lv_obj_set_height(ui_Container10, 173);
    lv_obj_set_x(ui_Container10, 199);
    lv_obj_set_y(ui_Container10, 372);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label59 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label59, 118);
    lv_obj_set_height(ui_Label59, 32);
    lv_obj_set_x(ui_Label59, -96);
    lv_obj_set_y(ui_Label59, -61);
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "存储状态");
    lv_obj_set_style_text_color(ui_Label59, lv_color_hex(0x25B782), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label59, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label59, lv_color_hex(0xE4FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label59, lv_color_hex(0x96FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label59, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label66 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label66, -108);
    lv_obj_set_y(ui_Label66, -23);
    lv_obj_set_align(ui_Label66, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label66, "eMMC:");
    lv_obj_set_style_text_font(ui_Label66, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label71 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label71, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label71, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label71, -96);
    lv_obj_set_y(ui_Label71, 19);
    lv_obj_set_align(ui_Label71, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label71, "上次存盘:");
    lv_obj_set_style_text_font(ui_Label71, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label72 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label72, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label72, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label72, -102);
    lv_obj_set_y(ui_Label72, 58);
    lv_obj_set_align(ui_Label72, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label72, "空间:");
    lv_obj_set_style_text_font(ui_Label72, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label73 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label73, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label73, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label73, 14);
    lv_obj_set_y(ui_Label73, -60);
    lv_obj_set_align(ui_Label73, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label73, "已存:");
    lv_obj_set_style_text_font(ui_Label73, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button16 = lv_button_create(ui_Image29);
    lv_obj_set_width(ui_Button16, 84);
    lv_obj_set_height(ui_Button16, 50);
    lv_obj_set_x(ui_Button16, 413);
    lv_obj_set_y(ui_Button16, 457);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Button16);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -4);
    lv_obj_set_y(ui_Label10, 1);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "返回");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label10, ui_event_Label10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);

}
