// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image25, &ui_img_screen9_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 2732
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 1534
    lv_obj_set_x(ui_Image25, -35);
    lv_obj_set_y(ui_Image25, -305);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button8 = lv_button_create(ui_Image25);
    lv_obj_set_width(ui_Button8, 130);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_x(ui_Button8, 339);
    lv_obj_set_y(ui_Button8, 499);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 25);
    lv_obj_set_y(ui_Label14, 1);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "返回");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Image25);
    lv_obj_set_width(ui_Label41, 196);
    lv_obj_set_height(ui_Label41, 32);
    lv_obj_set_x(ui_Label41, -249);
    lv_obj_set_y(ui_Label41, 92);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "AI智能决策辅助");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0x25B782), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label41, lv_color_hex(0xE4FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label41, lv_color_hex(0x96FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label41, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Image25);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 697);
    lv_obj_set_height(ui_Container7, 50);
    lv_obj_set_x(ui_Container7, 35);
    lv_obj_set_y(ui_Container7, 145);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -293);
    lv_obj_set_y(ui_Label9, 0);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "溶解氧:");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, -93);
    lv_obj_set_y(ui_Label52, -2);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "温度:");
    lv_obj_set_style_text_font(ui_Label52, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, 66);
    lv_obj_set_y(ui_Label54, 2);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "pH:");
    lv_obj_set_style_text_font(ui_Label54, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, 218);
    lv_obj_set_y(ui_Label55, -1);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "浊度:");
    lv_obj_set_style_text_font(ui_Label55, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9v = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label9v, 90); lv_obj_set_height(ui_Label9v, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label9v, -165); lv_obj_set_y(ui_Label9v, 0);
    lv_obj_set_align(ui_Label9v, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label9v, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_font(ui_Label9v, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52v = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label52v, 90); lv_obj_set_height(ui_Label52v, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label52v, 15); lv_obj_set_y(ui_Label52v, -2);
    lv_obj_set_align(ui_Label52v, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label52v, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_font(ui_Label52v, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54v = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label54v, 70); lv_obj_set_height(ui_Label54v, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label54v, 145); lv_obj_set_y(ui_Label54v, 2);
    lv_obj_set_align(ui_Label54v, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label54v, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_font(ui_Label54v, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55v = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label55v, 90); lv_obj_set_height(ui_Label55v, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label55v, 315); lv_obj_set_y(ui_Label55v, -1);
    lv_obj_set_align(ui_Label55v, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label55v, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_font(ui_Label55v, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_button_create(ui_Image25);
    lv_obj_set_width(ui_Button14, 135);
    lv_obj_set_height(ui_Button14, 50);
    lv_obj_set_x(ui_Button14, 287);
    lv_obj_set_y(ui_Button14, 234);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0x80C2A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label77 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label77, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label77, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label77, 2);
    lv_obj_set_y(ui_Label77, -2);
    lv_obj_set_align(ui_Label77, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label77, "智能建议");
    lv_obj_set_style_text_font(ui_Label77, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_button_create(ui_Image25);
    lv_obj_set_width(ui_Button15, 138);
    lv_obj_set_height(ui_Button15, 50);
    lv_obj_set_x(ui_Button15, 120);
    lv_obj_set_y(ui_Button15, 232);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0x80C2A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label81 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label81, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label81, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label81, 4);
    lv_obj_set_y(ui_Label81, 1);
    lv_obj_set_align(ui_Label81, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label81, "故障诊断");
    lv_obj_set_style_text_font(ui_Label81, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_button_create(ui_Image25);
    lv_obj_set_width(ui_Button13, 132);
    lv_obj_set_height(ui_Button13, 50);
    lv_obj_set_x(ui_Button13, -225);
    lv_obj_set_y(ui_Button13, 234);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0x80C2A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, 1);
    lv_obj_set_y(ui_Label51, -2);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "一键评价");
    lv_obj_set_style_text_font(ui_Label51, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button17 = lv_button_create(ui_Image25);
    lv_obj_set_width(ui_Button17, 132);
    lv_obj_set_height(ui_Button17, 50);
    lv_obj_set_x(ui_Button17, -47);
    lv_obj_set_y(ui_Button17, 232);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0x80C2A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label74 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label74, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label74, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label74, 1);
    lv_obj_set_y(ui_Label74, -2);
    lv_obj_set_align(ui_Label74, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label74, "运维回答");
    lv_obj_set_style_text_font(ui_Label74, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_Image25);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 620);
    lv_obj_set_height(ui_Container11, 229);
    lv_obj_set_x(ui_Container11, 28);
    lv_obj_set_y(ui_Container11, 395);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label56 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label56, 580); lv_obj_set_height(ui_Label56, 200);
    lv_obj_set_x(ui_Label56, 0); lv_obj_set_y(ui_Label56, 0);
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "点击按钮获取AI分析");
    lv_label_set_long_mode(ui_Label56, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_font(ui_Label56, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label14, ui_event_Label14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);

}
